= Отчет по лабораторной работе №7
Выполнила студентка группы КЭ-413, Кузнецова А.С.
:imagesdir: Pic
:toc:
:toc-title: Оглавление
:toclevels: 2
:figure-caption: Рисунок
:table-caption: Таблица

include::tituln7.adoc[]

== Таймеры в микроконтроллере STM32F411RET6

Таймеры в микроконтроллере STM32F411RET6 являются мощными аппаратными средствами, которые предоставляют возможности для измерения времени, создания сигналов, захвата событий, генерации прерываний и выполнения других задач. Этот микроконтроллер принадлежит семейству STM32F4, основанному на ядре ARM Cortex-M4, и оснащён различными типами таймеров.

=== Типы таймеров в STM32F411RET6

В STM32F411RET6 есть несколько видов таймеров, различающихся функциональностью и назначением:

1. Основные таймеры (Basic Timers):
* TIM6 и TIM7.
* Функции:
** Простейшие задачи, такие как генерация базового времени.
** Используются для задания временных интервалов или как источники времени для других модулей.
* Особенности:
** Только счётчик, без поддержки PWM, входного захвата и других сложных функций.
** Предназначены для работы с DAC (цифро-аналоговым преобразователем).

2. Общие таймеры (General-Purpose Timers):
* TIM2, TIM3, TIM4, TIM5.
* Функции:
** Генерация PWM-сигналов.
** Входной захват (для измерения частоты или ширины импульсов).
** Выходное сравнение (для генерации сигналов).
* Особенности:
** TIM2 и TIM5 имеют 32-разрядный счётчик.
** TIM3 и TIM4 имеют 16-разрядный счётчик.
** Поддерживают до 4 каналов (можно работать с несколькими сигналами одновременно).

4. Системный таймер (SysTick):
* Функции:
** Встроен в ядро ARM Cortex-M4.
** Используется для реализации системного времени в ОС реального времени (например, FreeRTOS).
* Особенности:
** Часть системной периферии и работает независимо от других таймеров.
** Простая настройка, используется часто для задач планирования.

=== Пример возможностей таймеров

1.Измерение времени:

* Таймеры можно использовать для точного отсчёта времени с разрешением до наносекунд (при высокой частоте тактирования).

2.Генерация PWM-сигналов:

* Например, для управления яркостью светодиодов, управления сервоприводами, двигателями.

3.Измерение частоты и ширины импульсов:

* Использование функций входного захвата (Input Capture).

4.Создание периодических прерываний:

* Для выполнения периодических задач, например, опроса датчиков.

5.Сложные задачи управления:

* Dead-time для управления мостами в инверторах или преобразователях.

=== Таймеры TIM2 и TIM5, основные особенности

* Таймеры 32 битные (то есть могут считать до 2^32), умеют работать:
- с инкрементальными энкодерами и датчиками Холла,
- несколько таймеров можно синхронизировать между собой.

* Таймеры могут использоваться для:
- Захвата сигнала (Защелкивать значение, когда на выводе порта например 0 сменился на 1)
- Сравнения (Считать до значения в регистре сравнения и установить/сбросить/переключить вывод порта)
- Генерации ШИМ (Генерировать прямоугольный сигнал с различной скважностью на вывод порта)
- Генерации одиночного импульса

Таймеры TIM2 и TIM5

* Таймеры могут генеририровать следующие события:
** Переполнение
** Захват сигнала
** Сравнение
** Событие-триггер

== Работа с системным таймером SysTick

Системный таймер SysTick, встроенный в ядро ARM Cortex-M4 микроконтроллеров STM32, используется для создания прерываний с заданной периодичностью. Для его подключения и настройки используются следующие шаги и команды:

[source, cpp]
----
#include "stkregisters.hpp" // for SystemTimer
#include "scbregisters.hpp" // for ISCR register
----

Далее приведен код, который реализует функцию задержки на заданное количество миллисекунд с использованием системного таймера (SysTick) и была  реализована функция delay().
Функция delay() реализует программную задержку с использованием системного таймера SysTick. Таймер конфигурируется на указанное время в миллисекундах, запускается, и выполнение программы приостанавливается до завершения отсчёта. 

[source, cpp]
----

void delay(uint32_t mseconds)
{
  assert (mseconds < 10000);
  const auto timerDelayCounts = (SystemCoreClock / 1000U) * mseconds;
  STK::LOAD::Write(timerDelayCounts - 1);
  STK::VAL::Write(0);
  STK::CTRL::ENABLE::Enable::Set();

    while(STK::CTRL::COUNTFLAG::NoOverflow::IsSet())
    {
    }
  
   STK::CTRL::ENABLE::Disable;
}

----

Код main():

[source, cpp]
----

int main()
{  
  RCC::AHB1ENR::GPIOAEN::Enable::Set() ;
  RCC::AHB1ENR::GPIOCEN::Enable::Set() ;
  GPIOA::MODER::MODER5::Output::Set() ;
  GPIOC::MODER::MODER5::Output::Set() ;
  GPIOC::MODER::MODER8::Output::Set() ;
  GPIOC::MODER::MODER9::Output::Set() ;
  
  Button <GPIOC, 13> button;

  Led<GPIOC, 5> led1;
  Led<GPIOC, 8> led2;
  Led<GPIOC, 9> led3;
  Led<GPIOA, 5> led4;
  
   tLeds leds = {
    &led1,
    &led2,
    &led3,
    &led4};
    
    
    AllMode allmode(leds);
    ChessMode chessmode(leds);
    TreeMode treemode(leds);
    
    tMode MODES = {
    &allmode,  
    &chessmode,
    &treemode  
    };
    ModeManager modeManager(MODES);
    modeManager.InitModeManager();

  for(;;) 
  {

    modeManager.UpdateModeManager();
    
    if(button.isClick())
    {
      modeManager.SwitchModeManager();
    }
    delay(300);
  }
    
  return 1;
}

----

== Настройка таймера TIM5

Таймер TIM5 — это универсальный 32-разрядный таймер общего назначения, который предоставляет широкий функционал для управления временными интервалами, генерации сигналов и измерений. Этот таймер отличается повышенной разрядностью, что делает его удобным для задач, требующих работы с длительными интервалами времени.

Основные возможности TIM5:

* 32-разрядный счётчик: Подходит для работы с длительными интервалами времени и высокоточной синхронизации.
* Частота тактирования:
** Работает на шине APB1, с частотой до 42 МГц.
** При делении APB1≠1 частота таймера удваивается, достигая 84 МГц.
* 4 канала: Позволяют одновременно использовать несколько режимов (например, ШИМ, входной захват).
* Поддержка режимов работы:
** ШИМ (PWM): Генерация сигналов с регулируемой частотой и коэффициентом заполнения.
** Input Capture: Измерение времени между событиями (ширина импульса, частота).
** Output Compare: Генерация сигналов в заданные моменты времени.
** Encoder Mode: Работа с энкодерами для отслеживания вращения и положения.

Режимы работы:

1.Генерация ШИМ:

** Управление яркостью светодиодов, двигателями и др.
** Настраивается через регистры сравнения (CCR1–CCR4).

2.Input Capture:

** Измерение входных сигналов, например, частоты или длительности импульсов.

3.Output Compare:

** Создание периодических сигналов или управление событиями.

4.Encoder Mode:

** Подходит для ра
боты с энкодерами для отслеживания положения и скорости вращения. 

Основные регистры TIM5:

. PSC (Prescaler): Делитель частоты входного сигнала.
. ARR (Auto Reload Register): Устанавливает период счётчика.
. CNT (Counter): Хранит текущее значение счётчика.
. CCR1–CCR4: Управляют каналами захвата/сравнения.
. CR1: Настройка основных параметров таймера.
. DIER: Разрешение прерываний и DMA-запросов.
. SR: Флаги состояния таймера. 

Разработка функции delay() на основе таймера TIM5.

Подключение таймера:

[source, cpp]
----
#include "tim5registers.hpp"

std::uint32_t SystemCoreClock = 16'000'000U;

extern "C" {
int __low_level_init(void)
{
  RCC::CR::HSION::On::Set();
  while (RCC::CR::HSIRDY::NotReady::IsSet())
  {

  }
  RCC::CFGR::SW::Hsi::Set();
  while (!RCC::CFGR::SWS::Hsi::IsSet())
  {

  }
  RCC::APB1ENR::TIM5EN::Enable::Set();
  return 1;
}
----


Функция осуществляет задержку с использованием таймера TIM5 микроконтроллера. Она проверяет входное значение mseconds на корректность, затем настраивает таймер: задаёт предделитель для работы с миллисекундами, устанавливает значения регистров автоперезагрузки (ARR) и счётчика (CNT), сбрасывает флаг прерывания (UIF) и запускает таймер. После этого функция в цикле ожидает окончания заданного времени, проверяя состояние флага прерывания. По завершении задержки таймер отключается, а флаг прерывания сбрасывается.

[source, cpp]
----
void delay(uint32_t mseconds)
{
  assert (mseconds < 10000);
  const auto timerDelayCounts = (SystemCoreClock / 1000U) * mseconds;
  TIM5::PSC::Write(timerDelayCounts-1U);
  TIM5::CR1::URS::Value1::Set();
  TIM5::ARR::Write(mseconds);
  TIM5::CNT::Write(0);
  TIM5::SR::UIF::Set(0);
  TIM5::CR1::CEN::Enable::Set(); 
    while(TIM5::SR::UIF::NoInterruptPending::IsSet())
    {
    }
   TIM5::CR1::CEN::Disable::Set();
   TIM5::SR::UIF::Set(0);
}
----
== Заключение

В данной работе были рассмотренны основные таймеры в микроконтроллере STM32F411RET6, их типы и примеры использования. Была проделана работа с системным таймером. Также был настроен таймер TIM5 с функцией delay().